#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TS="$(date +%Y%m%d_%H%M%S)"

export PORT="${PORT:-30001}"
export CSAHCA_DSV4_MODE="${CSAHCA_DSV4_MODE:-csahca}"
export CSAHCA_DSV4_REPLACE_OUTPUT="${CSAHCA_DSV4_REPLACE_OUTPUT:-0}"
export CSAHCA_DSV4_LIVE_COMPARE="${CSAHCA_DSV4_LIVE_COMPARE:-1}"
export CSAHCA_DSV4_TRACE_ABI="${CSAHCA_DSV4_TRACE_ABI:-1}"
export CSAHCA_DSV4_TRACE_FIRST_N="${CSAHCA_DSV4_TRACE_FIRST_N:-4}"
export CSAHCA_DSV4_TRACE_ABI_FIRST_N="${CSAHCA_DSV4_TRACE_ABI_FIRST_N:-2}"
export CSAHCA_DSV4_COMPARE_FORWARD_MODES="${CSAHCA_DSV4_COMPARE_FORWARD_MODES:-DECODE}"
export CSAHCA_DSV4_COMPARE_LAYER_IDS="${CSAHCA_DSV4_COMPARE_LAYER_IDS:-all}"
export CSAHCA_DSV4_COMPARE_MAX_Q="${CSAHCA_DSV4_COMPARE_MAX_Q:-8}"
export CSAHCA_DSV4_COMPARE_FIRST_N="${CSAHCA_DSV4_COMPARE_FIRST_N:-2}"
export CSAHCA_DSV4_COMPARE_MAX_CALLS="${CSAHCA_DSV4_COMPARE_MAX_CALLS:-512}"
export CSAHCA_DSV4_COMPARE_REQUIRE_FINITE_Q="${CSAHCA_DSV4_COMPARE_REQUIRE_FINITE_Q:-0}"
export CSAHCA_DSV4_COMPARE_MAX_ABS_Q="${CSAHCA_DSV4_COMPARE_MAX_ABS_Q:-0}"
export CSAHCA_DSV4_CAPTURE_LAYER_IDS="${CSAHCA_DSV4_CAPTURE_LAYER_IDS:-0,2,3}"
export CSAHCA_DSV4_CAPTURE_FORWARD_MODES="${CSAHCA_DSV4_CAPTURE_FORWARD_MODES:-DECODE}"
export CSAHCA_DSV4_CAPTURE_MAX_Q="${CSAHCA_DSV4_CAPTURE_MAX_Q:-4}"
export CSAHCA_DSV4_CAPTURE_FIRST_N="${CSAHCA_DSV4_CAPTURE_FIRST_N:-1}"
export CSAHCA_DSV4_CAPTURE_MAX_CALLS="${CSAHCA_DSV4_CAPTURE_MAX_CALLS:-0}"
export CSAHCA_DSV4_CAPTURE_CACHES="${CSAHCA_DSV4_CAPTURE_CACHES:-1}"
export LOG_FILE="${LOG_FILE:-/mnt/Data/yangpd/logs/dsv4_flash/csahca_shadow_compare_${TS}.log}"

if [[ -z "${SGLANG_EXTRA_ARGS:-}" ]]; then
  export SGLANG_EXTRA_ARGS="--disable-decode-cuda-graph"
fi

echo "Shadow compare launch: port=${PORT} replace=${CSAHCA_DSV4_REPLACE_OUTPUT} live_compare=${CSAHCA_DSV4_LIVE_COMPARE} log=${LOG_FILE}"
exec "${SCRIPT_DIR}/launch_patched_dsv4.sh"
